pull_request_rules:
  - name: Automatic merge security PRs when all status checks pass
    conditions:
      - author~=^(snyk-bot|dependabot\[bot\])$
      - status-success=security/snyk (coderbyheart)
      - status-success=tests
    actions:
      merge:
        method: rebase
        rebase_fallback: squash
        bot_account: coderbyheart
      label:
        add:
          - mergify
      rebase:
        bot_account: coderbyheart
