import { pattern } from './pattern'

describe('Pattern Generator', () => {
	it('should generate a pattern for the first phase', () => {
		const p = pattern(1)
		expect(p.next().value).toEqual(1)
		expect(p.next().value).toEqual(0)
		expect(p.next().value).toEqual(-1)
		expect(p.next().value).toEqual(0)
		expect(p.next().value).toEqual(1)
		expect(p.next().value).toEqual(0)
		expect(p.next().value).toEqual(-1)
		expect(p.next().value).toEqual(0)
	})
	it('should generate a pattern for the second phase', () => {
		const p = pattern(2)
		expect(p.next().value).toEqual(0)
		expect(p.next().value).toEqual(1)
		expect(p.next().value).toEqual(1)
		expect(p.next().value).toEqual(0)
		expect(p.next().value).toEqual(0)
		expect(p.next().value).toEqual(-1)
		expect(p.next().value).toEqual(-1)
		expect(p.next().value).toEqual(0)
		expect(p.next().value).toEqual(0)
		expect(p.next().value).toEqual(1)
		expect(p.next().value).toEqual(1)
		expect(p.next().value).toEqual(0)
		expect(p.next().value).toEqual(0)
		expect(p.next().value).toEqual(-1)
		expect(p.next().value).toEqual(-1)
		expect(p.next().value).toEqual(0)
		expect(p.next().value).toEqual(0)
	})
})
